name: stress-check

on:
  workflow_dispatch:

jobs:
  stress_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Manual application stress check (experimental)"
